# Generated by Django 5.1.5 on 2025-01-30 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='psychologistprofile',
            old_name='is_verified',
            new_name='is_admin_verified',
        ),
        migrations.RemoveField(
            model_name='psychologistprofile',
            name='is_active',
        ),
    ]
