# Generated by Django 5.1.5 on 2025-02-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emailverificationotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='mobile_number',
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='psychologistprofile',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
