# Generated by Django 5.1.5 on 2025-02-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_mobile_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile_images/'),
        ),
        migrations.AlterField(
            model_name='psychologistprofile',
            name='education_certificate',
            field=models.ImageField(upload_to='media/education-certificates/'),
        ),
        migrations.AlterField(
            model_name='psychologistprofile',
            name='experience_certificate',
            field=models.ImageField(upload_to='media/experience-certificates/'),
        ),
        migrations.AlterField(
            model_name='psychologistprofile',
            name='id_card',
            field=models.ImageField(upload_to='media/id-cards/'),
        ),
        migrations.AlterField(
            model_name='psychologistprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile_images/'),
        ),
    ]
