# Generated by Django 5.1.5 on 2025-02-15 06:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_usermedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermedia',
            name='image_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
