# Generated by Django 5.1.5 on 2025-02-15 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_usermedia_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermedia',
            name='media_file',
            field=models.ImageField(upload_to='test/'),
        ),
    ]
