# Generated by Django 5.1.5 on 2025-02-15 11:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_usermedia_media_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_image'),
        ),
        migrations.AlterField(
            model_name='psychologistprofile',
            name='education_certificate',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='education_certificate'),
        ),
        migrations.AlterField(
            model_name='psychologistprofile',
            name='experience_certificate',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='experience_certificate'),
        ),
        migrations.AlterField(
            model_name='psychologistprofile',
            name='id_card',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='id_card'),
        ),
        migrations.AlterField(
            model_name='psychologistprofile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_image'),
        ),
    ]
