# Generated by Django 5.1.5 on 2025-02-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_patientprofile_profile_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='psychologistprofile',
            old_name='is_admin_verified',
            new_name='is_admin_approved',
        ),
        migrations.AddField(
            model_name='psychologistprofile',
            name='approval_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
