# Generated by Django 5.1.5 on 2025-04-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_patientprofile_medical_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Patient', 'Patient'), ('Psychologist', 'Psychologist'), ('Admin', 'Admin')], db_index=True, default='Patient', max_length=20),
        ),
    ]
