# Generated by Django 5.1.5 on 2025-03-06 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_patientprofile_medical_history_and_more'),
        ('consultations', '0002_timeslot_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='consultation_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='psychologist',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='accounts.psychologistprofile'),
        ),
    ]
