# Generated by Django 5.1.5 on 2025-03-07 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_alter_consultation_consultation_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
