# Generated by Django 5.1.5 on 2025-03-08 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0005_consultation_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
