# Generated by Django 5.1.5 on 2025-04-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0007_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='consultation_status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20),
        ),
    ]
