# Generated by Django 5.1.5 on 2025-04-04 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0008_alter_consultation_consultation_status'),
        ('payments', '0005_alter_payment_payment_gateway'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='payments.payment'),
        ),
    ]
