# Generated by Django 5.1.5 on 2025-03-19 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_patientprofile_medical_history_and_more'),
        ('chat', '0003_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatthread',
            name='psychologist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psychologist_threads', to='accounts.psychologistprofile'),
        ),
        migrations.AlterField(
            model_name='chatthread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_threads', to='accounts.patientprofile'),
        ),
    ]
