# Generated by Django 5.1.5 on 2025-03-20 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0006_timeslot_is_expired'),
        ('video_call', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocallsession',
            name='consultation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consultations.consultation'),
        ),
    ]
