# Generated by Django 5.1.5 on 2025-04-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_wallet_wallettransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_gateway',
            field=models.CharField(choices=[('Razorpay', 'Razorpay'), ('Wallet', 'Wallet')], max_length=20),
        ),
    ]
